version: "3"

services:
  shop_backend:
    build: .
    entrypoint: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    env_file: .env
    ports:
      - "8000:8000"